from django.db import models

class Usuario(models.Model):
    id_usuario = models.AutoField(primary_key=True)
    nome = models.TextField(null = True)
    data_de_nasc = models.TextField(null = True)
    idade = models.IntegerField(null = True)
    cep = models.TextField(null = True)
    bairro = models.TextField(null = True)
    n_casa = models.IntegerField(null = True)
    telefone = models.IntegerField(null = True)
    email = models.TextField(null = True)
    profissao = models.TextField(null = True)
    especialidade = models.TextField(null = True)
    curso = models.TextField(null = True)
    historico = models.TextField(null = True)
    info = models.TextField(null = True)
    altura = models.IntegerField(null = True)
    peso = models.IntegerField(null = True)
    imc = models.FloatField(null = True)
    rg = models.IntegerField(null = True)
    cpf = models.IntegerField(null = True)
    estado_civil = models.TextField(null = True)
    raca = models.TextField(null = True)
    id_genero = models.TextField(null = True)
    escolaridade = models.TextField(null = True)
    data_atendimento = models.TextField(null = True)
    
#NUTRIÇÃO
    NUTRI_data_avaliacao = models.TextField(null = True)
    NUTRI_objetivo_da_orientacao = models.TextField(null = True)
    NUTRI_patologia = models.TextField(null = True)
    NUTRI_antecedentes = models.TextField(null = True)
    NUTRI_atividades = models.TextField(null = True)
    NUTRI_atividades_vezes_por_semana = models.IntegerField(null = True)
    NUTRI_ingestao_agua = models.IntegerField(null = True)
    NUTRI_alergia = models.TextField(null = True)
    NUTRI_cafe = models.TextField(null = True)
    NUTRI_lanche_manha = models.TextField(null = True)
    NUTRI_almoco = models.TextField(null = True)
    NUTRI_lanche_tarde = models.TextField(null = True)
    NUTRI_jantar = models.TextField(null = True)
    NUTRI_ceia = models.TextField(null = True)
    NUTRI_CC = models.TextField(null = True)
    NUTRI_CQ = models.TextField(null = True)
    NUTRI_CB = models.TextField(null = True)
    NUTRI_PCT = models.TextField(null = True)
    NUTRI_PCB = models.TextField(null = True)
    NUTRI_PCSE = models.TextField(null = True)
    NUTRI_PCSI = models.TextField(null = True)
    NUTRI_gordura = models.TextField(null = True)
    NUTRI_massa = models.TextField(null = True)
    NUTRI_idade_metab = models.TextField(null = True)
    NUTRI_gordura_visc = models.TextField(null = True)

# PSICOLOGIA
    PSICO_N_cadastro = models.IntegerField(null = True)
    PSICO_demanda_inicial = models.TextField(null = True)
    PSICO_observacoes = models.TextField(null = True)
    PSICO_transcricao = models.TextField(null = True)
    PSICO_estagiario_resp = models.TextField(null = True)
    PSICO_supervisor_resp = models.TextField(null = True)

    PSICO_escola = models.TextField(null = True)
    PSICO_ano_escolar = models.TextField(null = True)

    PSICO_resp_nome = models.TextField(null = True)
    PSICO_resp_data_de_nasc = models.TextField(null = True)
    PSICO_resp_idade = models.IntegerField(null = True)
    PSICO_resp_rg = models.IntegerField(null = True)
    PSICO_resp_cpf = models.IntegerField(null = True)
    PSICO_resp_cep = models.TextField(null = True)
    PSICO_resp_bairro = models.TextField(null = True)
    PSICO_resp_n_casa = models.IntegerField(null = True)
    PSICO_resp_telefone = models.IntegerField(null = True)
    PSICO_resp_email = models.TextField(null = True)
    PSICO_resp_parentesco = models.TextField(null = True)
    PSICO_resp_profissao = models.TextField(null = True)