# Generated by Django 4.2.5 on 2023-10-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('idade', models.IntegerField()),
                ('cep', models.TextField(max_length=255)),
                ('bairro', models.TextField(max_length=255)),
                ('n_casa', models.IntegerField()),
                ('telefone', models.IntegerField()),
                ('especialidade', models.TextField(blank=True)),
                ('curso', models.TextField()),
                ('historico', models.TextField(blank=True)),
                ('info', models.TextField(blank=True)),
            ],
        ),
    ]
